include:
  - compose.db.yaml

services:
  kroll:
    image: ghcr.io/collederas/kroll:v0.1.0-demo
    environment:
      KROLL_PROFILE: dev
      KROLL_DB_URL: jdbc:postgresql://postgres:5432/krolldb
      KROLL_DB_USER: postgres
      KROLL_DB_PASSWORD: postgres
      KROLL_JWT_SECRET: ZxQ6k1qJ7WmPz5Qz4y1R0+YJzKpZyPp0JxH0q8Q9v2E=
    networks:
      - kroll-net

  kroll-ui:
    image: ghcr.io/collederas/k-roll-ui:v0.1.0-demo
    networks:
      - kroll-net
    environment:
      VITE_API_URL: http://localhost:8080/api/

  proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/ingress-enabled/base.conf:/etc/nginx/ingress-enabled/base.conf:ro
      - ./infra/nginx/ingress-enabled/locations/api.conf:/etc/nginx/ingress-enabled/locations/api.conf:ro
      - ./infra/nginx/ingress-enabled/locations/ui.conf:/etc/nginx/ingress-enabled/locations/ui.conf:ro
    depends_on:
      - kroll
      - kroll-ui
    networks:
      - kroll-net

