services:
  kroll:
    image: kroll:local
    networks:
      - kroll-net

  kroll-ui:
    image: kroll-ui:local
    networks:
      - kroll-net

  proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/ingress.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - kroll
      - kroll-ui
    networks:
      - kroll-net
