services:
  kroll:
    image: ghcr.io/collederas/k-roll:v0.1.0
    networks:
      - kroll-net

  kroll-ui:
    image: ghcr.io/collederas/k-roll-ui:v0.1.0
    networks:
      - kroll-net

  proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/ingress.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - kroll
      - kroll-ui
    networks:
      - kroll-net
